/** Shared contracts for the pipeline. Nothing here mentions MCP or the browser. The core stays neutral. */

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------

export type DiagnosticCode =
  | 'json-parse-error'
  | 'unknown-context'
  | 'depth-limit'
  | 'no-structured-data'
  | 'action-skipped'
  | 'tool-limit'
  | 'field-truncated'
  // The two below are raised by an adapter rather than by the pipeline. They
  // live here anyway: `Diagnostic` is the one vocabulary a caller reads, and an
  // adapter with no way to say "I could not do my job" says nothing at all,
  // which reads exactly like a page that simply had no markup.
  | 'remap-failed'
  | 'no-webmcp-surface';

export interface Diagnostic {
  level: 'info' | 'warn' | 'error';
  code: DiagnosticCode;
  message: string;
}

// ---------------------------------------------------------------------------
// Extraction
// ---------------------------------------------------------------------------

export type SourceFormat = 'jsonld' | 'microdata' | 'rdfa';

export interface RawNode {
  data: JsonObject;
  format: SourceFormat;
}

export interface ExtractResult {
  nodes: RawNode[];
  diagnostics: Diagnostic[];
}

// ---------------------------------------------------------------------------
// Normalised graph
// ---------------------------------------------------------------------------

/** Points at another entity in the graph. Nested entities are hoisted into `nodes` and replaced with one of these. */
export interface EntityRef {
  ref: string;
}

export type PropertyValue = string | number | boolean | EntityRef;

export interface Entity {
  /** Always set: the resolved `@id`, or a generated blank node (`_:b0`). */
  id: string;
  /** Always an array, vocabulary prefixes stripped. Empty for nodes that carry no `@type`. */
  types: string[];
  /** Always arrays, even for a single value, so nothing downstream has to branch on single-vs-array. */
  props: Record<string, PropertyValue[]>;
  format: SourceFormat;
}

export interface EntityGraph {
  nodes: Map<string, Entity>;
  /** Entities nothing else points at, so the roots of the document. */
  roots: string[];
  diagnostics: Diagnostic[];
}

export const isRef = (v: PropertyValue): v is EntityRef =>
  typeof v === 'object' && v !== null && 'ref' in v;

// ---------------------------------------------------------------------------
// Tool descriptors: what the core emits
// ---------------------------------------------------------------------------

export interface JsonSchemaObject {
  type: 'object';
  properties: Record<string, JsonObject>;
  required?: string[];
  additionalProperties: false;
}

export interface ToolResult {
  content: Array<{ type: 'text'; text: string }>;
  isError?: boolean;
}

export interface ToolDescriptor {
  name: string;
  description: string;
  inputSchema: JsonSchemaObject;
  /**
   * Signals MCP clients use to decide what they can call without asking a human.
   * Read tools generated by the core are always `readOnlyHint: true`.
   */
  annotations: {
    readOnlyHint: boolean;
    openWorldHint: boolean;
  };
  execute: (args: Record<string, unknown>) => ToolResult | Promise<ToolResult>;
  source: {
    kind: 'read' | 'action' | 'custom';
    entityId?: string;
    entityType?: string;
  };
}
